global:
  clusterName: demo-env
  managedBy: ocp-platform

tenants:
  - name: tenant-a
    quota:
      requests.cpu: "6"
      requests.memory: 16Gi
      limits.cpu: "12"
      limits.memory: 32Gi
      pods: "30"
    limits:
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
    denyAllIngress: true
    redisNetworkPolicy: true
  - name: tenant-b
    quota:
      requests.cpu: "6"
      requests.memory: 16Gi
      limits.cpu: "12"
      limits.memory: 32Gi
      pods: "30"
    limits:
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
    denyAllIngress: true
    redisNetworkPolicy: true
