apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operatorNamespace }}
  labels:
    {{- include "shared-operators.labels" . | nindent 4 }}
    platform.ocp-gitops.io/role: operators
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: platform-shared-operators
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "shared-operators.labels" . | nindent 4 }}
spec:
  targetNamespaces:
    - {{ .Values.operatorNamespace }}
---
{{- range .Values.operators }}
{{- if .enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.operatorNamespace }}
  labels:
    {{- include "shared-operators.labels" $ | nindent 4 }}
spec:
  channel: {{ .channel }}
  installPlanApproval: Automatic
  name: {{ .package }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace }}
---
{{- end }}
{{- end }}
