global:
  clusterName: demo-env
  managedBy: ocp-platform

namespaces:
  - name: platform-shared
    labels:
      platform.ocp-gitops.io/role: shared-services
  - name: platform-ingress
    labels:
      platform.ocp-gitops.io/role: ingress
  - name: redis-enterprise
    labels:
      app.kubernetes.io/part-of: redis-enterprise
      platform.ocp-gitops.io/role: operators
